### PR TITLE
dwc2 patch for P4wnP1 successor

### PR DESCRIPTION
**Pull request by mame82**
As discussed on twitter here is the PR for a USB driver patch needed by P4wnP1 successor.
The patch does the following:
- adds a netlink multicast socket, which sends on group 24
- If dwc2 core operates in gadget mode, everytime the device is connected to a host interrupt is fired with USBRST flag set. If the gadget is disconnected from host, a interrupt is fired with no flag set. The patched dwc2 dirver monitors these two interrupt events. In case the state changes between two occuring interrupts, a netlink message is sent to user space on the multicast channel.
- A netlink message of `0x00` indicates that the USB gadget disconnected, a message of `0x01` indicates a connection.
- The aforementioned events occur when a gadget is initialized or de-initialized via configfs, too. (As effectively a new device is connected to the target host).
- There should be no interference with the default behavior of dwc2

As I keep P4wnP1 successor in a private repo till release, I provide a test client to read back the events for testing in the following repo:
https://github.com/mame82/dwc2_patch_userspace_test

The possibility to detect host connected/disconnected events in gadget mode with dwc2, could be of use for others, even if they don't use P4wnP1.

### CODE REVIEW

**Comment by Re4son** [comment]
Merged into rpi-4.14.62-p4wnp1.
1st run - cross-compiling - completed ok
2nd run - native armel kernel - completed ok (re4son_kernel_armel_4.14.62-20181003.tar.xz)
3rd run - native armel headers - completed ok (re4son_headers_armel_4.14.62-20181004.tar.xz)
4th run - packaging - completed ok (re4son-kernel_4.14.62-20181004.tar.xz)

Merged commit f945604a57dbaae259b1ca061b16b84f9db87f0e into rpi-4.14.62-p4wnp1
1st run - cross-compiling - completed ok
2nd run - native armel kernel - completed ok (re4son_kernel_armel_4.14.62-20181004.tar.xz)
3rd run - native armel headers - running
4th run - packaging - scheduled

Test after completion, merge into  rpi-4.14.62-re4son & master and release kali-pi image - ETA 5/10/2018

**Comment by mame82** [comment]
Urgent, the already merged PR could cause kernel panic if dwc2 interrupt handler stalls. Fixed in the last commit.
Sorry for this.

**Comment by Re4son** [comment]
No probs. I've merged the latest commit into rpi-4.14.62-p4wnp1 and put it back in the oven.
Should be ready tomorrow.

**Comment by Re4son** [comment]
Merged into rpi-4.14.62-p4wnp1.
Please let me know how you go with this and I'll update it to rpi-4.14.71-p4wnp1.
Once you are happy with everything I'll merge it into my mainline, ok?

**Comment by mame82** [comment]
Thx, was already testing 4.14.71 here:

https://github.com/mame82/re4son-raspberrypi-linux/commit/eee2786c6d3110cbdc8f0bf6fe3960a99f0f4fd2

Unfortunately I stumpled across an issue with nexmon (exists even without my additional changes).

See here for reference:
https://github.com/seemoo-lab/nexmon/issues/222

It seems the broadcom firmware version  used by nexmon (7.45.41.46) crashes on current 4.14.x kernels. According to several forums this is solved with a newer firmware 
(7.45.98.38).

Migrating nexmon to the newer firmware isn't an easy task, as it involves reversing large firmware parts to find correct hook addresses (for the old firmware this took roughly 6 weeks).

I'm currently not sure how to deal with that problem .

**Comment by Re4son** [comment]
Any reason for not sticking with 4.9.80 for now?
I can backport my updates, create a -p4wnp1 branch and you'd be ready to go

**Pull request merged**
